[General]
network = Luo2021Network
sim-time-limit = 10s

# Enable IEEE 802.1Qci ingress filtering
*.viuSwitch.hasIngressTrafficFiltering = true
*.vcuSwitch.hasIngressTrafficFiltering = true
#*.viuSwitch.bridging.streamFilter.ingress.typename = "src.psfp.PSFPIngress"
#*.vcuSwitch.bridging.streamFilter.ingress.typename = "src.psfp.PSFPIngress"
# Ethernet speed
*.*.eth[*].bitrate = 100Mbps

# Enable TAS
*.viuSwitch.hasEgressTrafficShaping = true
*.vcuSwitch.hasEgressTrafficShaping = true

# 8 traffic classes
*.viuSwitch.eth[*].macLayer.queue.numTrafficClasses = 8
*.vcuSwitch.eth[*].macLayer.queue.numTrafficClasses = 8

# 500 us cycle
*.viuSwitch.eth[*].macLayer.queue.transmissionGate[*].durations = [250us,250us]
*.vcuSwitch.eth[*].macLayer.queue.transmissionGate[*].durations = [250us,250us]

# Priority 6 radar open first
*.viuSwitch.eth[*].macLayer.queue.transmissionGate[6].initiallyOpen = true

# Priority 5 AV streams open second
*.viuSwitch.eth[*].macLayer.queue.transmissionGate[5].initiallyOpen = false

*.vcuSwitch.eth[*].macLayer.queue.transmissionGate[6].initiallyOpen = true
*.vcuSwitch.eth[*].macLayer.queue.transmissionGate[5].initiallyOpen = false

#########################
# AV1 video stream
#########################

*.av1.numApps = 1
*.av1.app[0].typename = "UdpSourceApp"
*.av1.app[0].io.destAddress = "centralHost"
*.av1.app[0].io.destPort = 5001
*.av1.app[0].source.packetLength = 2000B
*.av1.app[0].source.productionInterval = 90us

#########################
# AV2 video stream
#########################

*.av2.numApps = 1
*.av2.app[0].typename = "UdpSourceApp"
*.av2.app[0].io.destAddress = "centralHost"
*.av2.app[0].io.destPort = 5002
*.av2.app[0].source.packetLength = 500B
*.av2.app[0].source.productionInterval = 90us

#########################
# Radar stream
#########################

*.radarNode.numApps = 1
*.radarNode.app[0].typename = "UdpSourceApp"
*.radarNode.app[0].io.destAddress = "centralHost"
*.radarNode.app[0].io.destPort = 5003
*.radarNode.app[0].source.packetLength = 64B
*.radarNode.app[0].source.productionInterval = 500us

#########################
# Best effort source
#########################

*.centralHost.numApps = 4

*.centralHost.app[0].typename = "UdpSinkApp"

*.centralHost.app[0].io.localPort = 5001

#########################
# Sinks
#########################

*.centralHost.app[1].typename = "UdpSinkApp"
*.centralHost.app[1].io.localPort = 5002

*.centralHost.app[2].typename = "UdpSinkApp"
*.centralHost.app[2].io.localPort = 5003

*.centralHost.app[3].typename = "UdpSinkApp"
*.centralHost.app[3].io.localPort = 5004

#########################
# Control stream (S4)
#########################

*.zonalHost.numApps = 1
*.zonalHost.app[0].typename = "UdpSourceApp"
*.zonalHost.app[0].io.destAddress = "centralHost"
*.zonalHost.app[0].io.destPort = 5004
*.zonalHost.app[0].source.packetLength = 20B
*.zonalHost.app[0].source.productionInterval = 500us

#################################################
# PSFP TEST - AV1 ONLY
#################################################

*.av1.hasOutgoingStreams = true

*.av1.bridging.streamIdentifier.identifier.mapping = [{stream: "av1", packetFilter: expr(has(udp))}]

*.av1.bridging.streamCoder.encoder.mapping = [{stream: "av1", pcp: 5}]

*.viuSwitch.bridging.streamCoder.decoder.mapping = [{source: "av1", pcp: 5, stream: "av1"}]
*.vcuSwitch.bridging.streamCoder.decoder.mapping = [{source: "av1", pcp: 5, stream: "av1"}]

*.viuSwitch.bridging.streamFilter.ingress.numStreams = 1
*.vcuSwitch.bridging.streamFilter.ingress.numStreams = 1

*.viuSwitch.bridging.streamFilter.ingress.classifier.mapping = {"av1": 0}
*.vcuSwitch.bridging.streamFilter.ingress.classifier.mapping = {"av1": 0}

*.viuSwitch.bridging.streamFilter.ingress.meter[0].typename = "SingleRateTwoColorMeter"
*.vcuSwitch.bridging.streamFilter.ingress.meter[0].typename = "SingleRateTwoColorMeter"

*.viuSwitch.bridging.streamFilter.ingress.meter[0].committedInformationRate = 50Mbps
*.viuSwitch.bridging.streamFilter.ingress.meter[0].committedBurstSize = 10kB

*.vcuSwitch.bridging.streamFilter.ingress.meter[0].committedInformationRate = 50Mbps
*.vcuSwitch.bridging.streamFilter.ingress.meter[0].committedBurstSize = 10kB

#################################################
# Stream decoding at destination host
#################################################

*.centralHost.hasIncomingStreams = true
*.centralHost.bridging.streamCoder.decoder.mapping = [{vlan: 1, stream: "avStream"}]

#################################################
# PCAP Recording
#################################################

#*.viuSwitch.recordPcap = true
#*.vcuSwitch.recordPcap = true
#*.centralHost.recordPcap = true
