[General]
network = Luo2021Network
sim-time-limit = 1s

# Ethernet speed
*.*.eth[*].bitrate = 100Mbps

# Enable TAS
*.viuSwitch.hasEgressTrafficShaping = true
*.vcuSwitch.hasEgressTrafficShaping = true

# 8 traffic classes
*.viuSwitch.eth[*].macLayer.queue.numTrafficClasses = 8
*.vcuSwitch.eth[*].macLayer.queue.numTrafficClasses = 8

# 500 us cycle
*.viuSwitch.eth[*].macLayer.queue.transmissionGate[*].durations = [250us,250us]
*.vcuSwitch.eth[*].macLayer.queue.transmissionGate[*].durations = [250us,250us]

# Priority 6 radar open first
*.viuSwitch.eth[*].macLayer.queue.transmissionGate[6].initiallyOpen = true

# Priority 5 AV streams open second
*.viuSwitch.eth[*].macLayer.queue.transmissionGate[5].initiallyOpen = false

*.vcuSwitch.eth[*].macLayer.queue.transmissionGate[6].initiallyOpen = true
*.vcuSwitch.eth[*].macLayer.queue.transmissionGate[5].initiallyOpen = false

#########################
# AV1 video stream
#########################

*.av1.numApps = 1
*.av1.app[0].typename = "UdpSourceApp"
*.av1.app[0].io.destAddress = "centralHost"
*.av1.app[0].io.destPort = 5001
*.av1.app[0].source.packetLength = 500B
*.av1.app[0].source.productionInterval = 90us

#########################
# AV2 video stream
#########################

*.av2.numApps = 1
*.av2.app[0].typename = "UdpSourceApp"
*.av2.app[0].io.destAddress = "centralHost"
*.av2.app[0].io.destPort = 5002
*.av2.app[0].source.packetLength = 500B
*.av2.app[0].source.productionInterval = 90us

#########################
# Radar stream
#########################

*.radarNode.numApps = 1
*.radarNode.app[0].typename = "UdpSourceApp"
*.radarNode.app[0].io.destAddress = "centralHost"
*.radarNode.app[0].io.destPort = 5003
*.radarNode.app[0].source.packetLength = 64B
*.radarNode.app[0].source.productionInterval = 500us

#########################
# Best effort source
#########################

*.centralHost.numApps = 4

*.centralHost.app[0].typename = "UdpSinkApp"

*.centralHost.app[0].io.localPort = 5001

#########################
# Sinks
#########################

*.centralHost.app[1].typename = "UdpSinkApp"
*.centralHost.app[1].io.localPort = 5002

*.centralHost.app[2].typename = "UdpSinkApp"
*.centralHost.app[2].io.localPort = 5003

*.centralHost.app[3].typename = "UdpSinkApp"
*.centralHost.app[3].io.localPort = 5004

#########################
# Control stream (S4)
#########################

*.zonalHost.numApps = 1
*.zonalHost.app[0].typename = "UdpSourceApp"
*.zonalHost.app[0].io.destAddress = "centralHost"
*.zonalHost.app[0].io.destPort = 5004
*.zonalHost.app[0].source.packetLength = 20B
*.zonalHost.app[0].source.productionInterval = 500us

