[General]
network = Luo2021Network
sim-time-limit = 1s

**.eth[*].bitrate = 100Mbps

# Enable gPTP everywhere
*.*.hasTimeSynchronization = true

# CentralHost acts as grandmaster
*.centralHost.gptp.gptpNodeType = "MASTER_NODE"
*.centralHost.gptp.masterPorts = ["eth0"]

# Other nodes are slaves
*.av1.gptp.gptpNodeType = "SLAVE_NODE"
*.av2.gptp.gptpNodeType = "SLAVE_NODE"
*.radarNode.gptp.gptpNodeType = "SLAVE_NODE"
*.zonalHost.gptp.gptpNodeType = "SLAVE_NODE"

*.viuSwitch.gptp.gptpNodeType = "SLAVE_NODE"
*.vcuSwitch.gptp.gptpNodeType = "SLAVE_NODE"


# Clock oscillator configuration (from INET gPTP showcase)
**.oscillator.nominalTickLength = 10ns
**.oscillator.changeInterval = 12.5ms
**.oscillator.driftRate = uniform(-100ppm, 100ppm)
**.oscillator.driftRateChange = uniform(-1ppm, 1ppm)
**.oscillator.driftRateChangeUpperLimit = 100ppm
**.oscillator.driftRateChangeLowerLimit = -100ppm


# Override previous master selection
*.centralHost.gptp.gptpNodeType = "SLAVE_NODE"

*.vcuSwitch.gptp.gptpNodeType = "MASTER_NODE"
*.vcuSwitch.gptp.masterPorts = ["eth0","eth1"]


# Make CentralHost the grandmaster
*.centralHost.gptp.gptpNodeType = "MASTER_NODE"
*.centralHost.gptp.slavePort = ""
*.centralHost.gptp.masterPorts = ["eth0"]

# Reset switches to slaves
*.vcuSwitch.gptp.gptpNodeType = "SLAVE_NODE"
*.viuSwitch.gptp.gptpNodeType = "SLAVE_NODE"

